import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { gunzipSync, gzipSync } from "node:zlib";
import { describe, expect, it } from "vitest";
import type { JojoFragment, TimesDateManifest, TimesSourceIndex, TimesTimelineDay, TimesTimelineIndex, TimesTimelinePage } from "@jojo/content";
import { buildNewsDelivery, readJoxJson } from "../src/delivery-writer.js";
import { articleId, sha256 } from "../src/identity.js";
import { writeCanonicalSource, type CanonicalArticle, type CanonicalDateIndex, type CanonicalArticleRef } from "../src/process/canonical-writer.js";
import type { ProcessedCandidate } from "../src/process/article.js";
import { acceptChinanewsCanonicalAsset } from "../src/sources/chinanews/images.js";
import type { SourceCaptureManifest, SourceConfig } from "../src/types.js";

// The identities/timestamp reproduce the production incident; body is synthetic.
const source: SourceConfig = { id: "chinanews", name: "China News", language: "zh-CN", publicationTimeZone: "Asia/Shanghai",
  discovery: { kind: "sitemap", url: "https://example.test/sitemap.xml", maximumPages: 1 },
  content: { priority: ["captured-page"], parser: "chinanews" }, fetch: { strategy: "direct-first", bpc: false },
  health: { minimumCandidates: 1 }, enabled: true };
const manifest: SourceCaptureManifest = { formatVersion: "jojo-times-raw-source-run/2", runId: "identity-regression",
  sourceId: source.id, sourceName: source.name, publicationTimeZone: source.publicationTimeZone,
  startedAt: "2026-09-06T10:50:00Z", completedAt: "2026-09-06T10:51:00Z", discovery: source.discovery,
  candidateCount: 2, fullCount: 2, summaryCount: 0, metadataCount: 0, networkExchangeCount: 0, objects: [],
  captureStatus: "pages-complete", healthStatus: "healthy", complete: true };
const dateObject = "canonical/chinanews/dates/2026/09/2026-09-06.json.gz";
function candidate(section: string): ProcessedCandidate {
  const url = `https://www.chinanews.com.cn/${section}/2026/09-06/10691490.shtml`;
  return { articleId: articleId(source.id, url), sourceId: source.id, sourceName: source.name, sourceUrl: url, canonicalUrl: url,
    title: "Same report under two publisher sections", language: source.language, publishedAt: "2026-09-06T09:57:27.000Z",
    processedBody: "<p>Identical synthetic article content.</p>", contentStatus: "full", authors: [], publisherCategories: [], assets: [] };
}
const first = candidate("gj");
const second = candidate("sh");

async function fixture() {
  const output = await mkdtemp(path.join(os.tmpdir(), "jojo-times-canonical-identity-"));
  const read = async <T>(object: string): Promise<T> => JSON.parse(gunzipSync(await readFile(path.join(output, object))).toString("utf8"));
  const write = (candidates: ProcessedCandidate[], acceptCanonicalAsset = acceptChinanewsCanonicalAsset) => writeCanonicalSource(
    output, source, manifest, "raw/chinanews/runs/identity/manifest.json", candidates, "test-raw-revision", { acceptCanonicalAsset },
  );
  const writeObject = async (object: string, value: unknown) => writeFile(path.join(output, object), gzipSync(`${JSON.stringify(value)}\n`));
  const assertReferences = async () => {
    const index = await read<CanonicalDateIndex>(dateObject);
    expect(new Set(index.articles.map((ref) => ref.object)).size).toBe(index.articles.length);
    for (const ref of index.articles) expect(await read<CanonicalArticle>(ref.object)).toMatchObject({
      articleId: ref.articleId, source: { id: source.id }, contentHash: ref.contentHash, publishedAt: ref.publishedAt,
    });
    return index;
  };
  // Construct the exact pre-fix hash algorithm, not a hash generated by the
  // new writer. Existing content-only refs must stay readable without rewrite.
  const seedLegacy = async (candidates: ProcessedCandidate[]) => {
    const result = await write(candidates, () => true);
    const refs: CanonicalArticleRef[] = [];
    for (const ref of result.articles) {
      const article = await read<CanonicalArticle>(ref.object);
      const contentHash = sha256(JSON.stringify({ title: article.title, publishedAt: article.publishedAt, updatedAt: article.updatedAt,
        body: article.body, assets: article.assets.map((asset) => [asset.id, asset.sha256, asset.role, asset.afterBlock, asset.presentation]),
        translations: article.translations }));
      const object = `canonical/chinanews/articles/${contentHash}.json.gz`;
      await writeObject(object, { ...article, contentHash });
      refs.push({ ...ref, object, contentHash });
    }
    await writeObject(dateObject, { ...await read<CanonicalDateIndex>(dateObject), articles: refs });
    return refs;
  };
  return { output, read, write, writeObject, assertReferences, seedLegacy };
}

async function deliveryFixture() {
  const f = await fixture();
  const deliveryRoot = path.join(f.output, "delivery");
  const read = async <T>(object: string): Promise<T> => readJoxJson<T>(await readFile(path.join(deliveryRoot, object)), object);
  type Previous = { day: TimesTimelineDay; index: TimesTimelineIndex; sourceIndex: TimesSourceIndex };
  const publish = async (rows: ProcessedCandidate[], previous?: Previous) => {
    const canonical = await f.write(rows);
    const result = await buildNewsDelivery({ workspaceRoot: f.output, deliveryRoot, generatedAt: "2026-09-06T12:00:00Z",
      sources: [source], process: { sources: [canonical] }, ...(previous ? {
        previousTimelineDays: new Map([[previous.day.date, previous.day]]), previousTimelineIndex: previous.index,
        previousSourceIndexes: new Map([[source.id, previous.sourceIndex]]),
      } : {}),
    });
    const day = await read<TimesTimelineDay>("content/timeline/dates/2026/09/2026-09-06.jox");
    const index = await read<TimesTimelineIndex>(result.timelineIndexObject);
    const sourceIndex = await read<TimesSourceIndex>("content/newspapers/chinanews/index.jox");
    return { day, index, sourceIndex, result };
  };
  const assertOnePublication = async (published: Previous) => {
    expect(published.day.articles).toHaveLength(1);
    expect(published.index.dates[0]).toMatchObject({ articleCount: 1, pages: [{ articleCount: 1 }] });
    const page = await read<TimesTimelinePage>("content/timeline/dates/2026/09/2026-09-06/page-0001.jox");
    expect(page.articles).toEqual(published.day.articles);
    const manifest = await read<TimesDateManifest>("content/newspapers/chinanews/dates/2026/09/2026-09-06.jox");
    expect(manifest.contentStats?.articleCount).toBe(1);
    expect(manifest.content.articles).toHaveLength(1);
    expect(manifest.content.articles?.[0]).toMatchObject({ id: published.day.articles[0]!.id, object: published.day.articles[0]!.articleObject });
    const fragment = await read<JojoFragment>(published.day.articles[0]!.articleObject);
    expect(fragment.fragmentId).toBe(published.day.articles[0]!.id);
    expect(fragment.title).toBe(published.day.articles[0]!.title);
  };
  return { ...f, publish, assertOnePublication };
}

describe("identity-safe Canonical object keys", () => {
  it("keeps same-content identities distinct within one batch and a later retained-only pass", async () => {
    const f = await fixture();
    expect([first.articleId, second.articleId]).toEqual(["chinanews:239abe070700e4310c3d74a3", "chinanews:1d67ce5cf5d713fd807d40a4"]);
    const result = await f.write([first, second]);
    expect(result.articles[0]!.contentHash).not.toBe(result.articles[1]!.contentHash);
    expect((await f.assertReferences()).articles).toHaveLength(2);
    expect((await f.read<CanonicalArticle>(result.articles[0]!.object)).canonicalUrl).toBe(first.canonicalUrl);
    expect((await f.read<CanonicalArticle>(result.articles[1]!.object)).canonicalUrl).toBe(second.canonicalUrl);
    expect((await f.write([])).articles).toEqual([]);
    expect((await f.assertReferences()).articles).toHaveLength(2);
  });

  it.each([false, true])("does not overwrite a retained article before validation (legacy hash: %s)", async (legacy) => {
    const f = await fixture();
    const [oldRef] = legacy ? await f.seedLegacy([first]) : (await f.write([first])).articles;
    const oldBytes = await readFile(path.join(f.output, oldRef!.object));
    const result = await f.write([second]);
    expect(result.articles).toHaveLength(1);
    expect(result.articles[0]!.object).not.toBe(oldRef!.object);
    expect(await readFile(path.join(f.output, oldRef!.object))).toEqual(oldBytes);
    expect((await f.assertReferences()).articles).toContainEqual(oldRef);
    expect((await f.write([])).articles).toEqual([]);
  });

  it("refreshes a legacy identity once, keeps stable hashes for retries, and versions content changes", async () => {
    const f = await fixture();
    const [legacy] = await f.seedLegacy([first]);
    const refreshed = await f.write([first]);
    expect(refreshed.articles[0]!.object).not.toBe(legacy!.object);
    expect((await f.write([first])).articles).toEqual(refreshed.articles);
    const changed = await f.write([{ ...first, processedBody: "<p>Updated content.</p>" }]);
    expect(changed.articles[0]!.object).not.toBe(refreshed.articles[0]!.object);
    expect((await f.assertReferences()).articles).toEqual(changed.articles);
    expect((await f.read<CanonicalArticle>(legacy!.object)).articleId).toBe(first.articleId);
  });

  it("does not merge retained identities when asset cleanup makes their content identical", async () => {
    const f = await fixture();
    const withAd = (row: ProcessedCandidate, id: string): ProcessedCandidate => ({ ...row, assets: [{ id, type: "image", role: "content",
      sourceUrl: "https://www.chinanews.com.cn/ad2008/banner.jpg", rawObject: `raw/chinanews/assets/${id}.jpg`,
      mediaType: "image/jpeg", size: 1, sha256: id }] });
    const oldRefs = await f.seedLegacy([withAd(first, "ad-a"), withAd(second, "ad-b")]);
    expect(oldRefs[0]!.object).not.toBe(oldRefs[1]!.object);
    const migrated = await f.write([]);
    expect(migrated.articles).toHaveLength(2);
    expect((await f.assertReferences()).articles).toHaveLength(2);
    for (const ref of migrated.articles) expect((await f.read<CanonicalArticle>(ref.object)).assets).toEqual([]);
    expect((await f.write([])).articles).toEqual([]);
  });

  it("still fails closed on a pre-existing article/ref identity mismatch", async () => {
    const f = await fixture();
    const [ref] = await f.seedLegacy([first]);
    await f.writeObject(ref!.object, { ...await f.read<CanonicalArticle>(ref!.object), articleId: second.articleId });
    const indexBytes = await readFile(path.join(f.output, dateObject));
    await expect(f.write([])).rejects.toThrow(`Invalid retained Canonical article for ${first.articleId}`);
    expect(await readFile(path.join(f.output, dateObject))).toEqual(indexBytes);
  });
});

describe("China News alias publication", () => {
  it("stores both Raw identities but publishes one article in source, timeline and page lists", async () => {
    const f = await deliveryFixture();
    const published = await f.publish([first, second]);
    expect((await f.assertReferences()).articles).toHaveLength(2);
    expect(published.result.articles).toBe(1);
    await f.assertOnePublication(published);
    const reversed = await f.publish([second, first]);
    expect(reversed.day.articles[0]!.id).toBe(published.day.articles[0]!.id);
  });

  it("retains the published ID/link across batches and retries when the alias is not newer", async () => {
    const f = await deliveryFixture();
    const original = await f.publish([first]);
    await f.seedLegacy([first]); // Real upgrade path: old hash + new alias.
    const next = await f.publish([second], original);
    expect(next.day.articles[0]).toEqual(original.day.articles[0]);
    expect(next.result.articles).toBe(0); // Alias was built, but not added to lists.
    await f.assertOnePublication(next);
    const retry = await f.publish([second], next);
    expect(retry.day.articles).toEqual(next.day.articles);
    await f.assertOnePublication(retry);
    expect((await f.assertReferences()).articles).toHaveLength(2);
  });

  it("selects a newer publisher revision as a whole record without reverting on an older retry", async () => {
    const f = await deliveryFixture();
    const original = await f.publish([first]);
    const update = { ...second, updatedAt: "2026-09-06T11:00:00Z", title: "Updated publisher report", processedBody: "<p>Updated report body.</p>" };
    const next = await f.publish([update], original);
    expect(next.day.articles[0]).toMatchObject({ id: second.articleId, title: update.title, url: second.canonicalUrl });
    await f.assertOnePublication(next);
    const retry = await f.publish([first], next);
    expect(retry.day.articles).toEqual(next.day.articles);
    await f.assertOnePublication(retry);
  });

  it("cleans already-published aliases on a restored day, even with no new articles", async () => {
    const f = await deliveryFixture();
    const a = await f.publish([first]);
    const b = await f.publish([second]);
    const previous = { ...a, day: { ...a.day, articles: [...a.day.articles, ...b.day.articles] } };
    const cleaned = await f.publish([], previous);
    await f.assertOnePublication(cleaned);
    expect(cleaned.result.dates).toEqual(["2026-09-06"]);
  });

  it("does not merge same-content articles with different manuscript numbers", async () => {
    const f = await deliveryFixture();
    const otherUrl = second.canonicalUrl.replace("10691490", "10691491");
    const published = await f.publish([first, { ...second, articleId: articleId(source.id, otherUrl), canonicalUrl: otherUrl }]);
    expect(published.day.articles).toHaveLength(2);
    expect(published.result.articles).toBe(2);
  });
});
