import { describe, expect, it, vi } from "vitest";
import type { JojoAuthClient } from "../src/client";
import { createPersonalInvitationRepository } from "../src/invitations";

describe("personal invitation repository", () => {
  it("returns the explicit unallocated status", async () => {
    const status = { allocated: false, redeemed: false } as const;
    const rpc = vi.fn().mockResolvedValue({ data: status, error: null });
    const repository = createPersonalInvitationRepository({
      rpc,
    } as unknown as JojoAuthClient);

    await expect(repository.getStatus()).resolves.toEqual(status);
  });

  it("loads the reusable plaintext code and its lifecycle metadata", async () => {
    const rpc = vi.fn().mockResolvedValue({
      data: {
        allocated: true,
        code: "K7MP4X",
        redeemed: false,
        expires_at: "2026-09-01T00:00:00Z",
        disabled: false,
      },
      error: null,
    });
    const repository = createPersonalInvitationRepository({
      rpc,
    } as unknown as JojoAuthClient);

    await expect(repository.getStatus()).resolves.toMatchObject({
      allocated: true,
      code: "K7MP4X",
      redeemed: false,
    });
    expect(rpc).toHaveBeenCalledWith("get_personal_invitation_status");
  });

  it("returns the plaintext generated by the database", async () => {
    const invitation = {
      code: "K7MP4X",
      expires_at: "2026-09-01T00:00:00Z",
    };
    const rpc = vi.fn().mockResolvedValue({ data: [invitation], error: null });
    const repository = createPersonalInvitationRepository({
      rpc,
    } as unknown as JojoAuthClient);

    await expect(repository.generate()).resolves.toEqual(invitation);
    expect(rpc).toHaveBeenCalledWith("generate_personal_signup_invitation");
  });

  it("does not hide database errors", async () => {
    const failure = {
      code: "P0001",
      message: "Personal invitation has already been redeemed.",
    };
    const rpc = vi.fn().mockResolvedValue({ data: null, error: failure });
    const repository = createPersonalInvitationRepository({
      rpc,
    } as unknown as JojoAuthClient);

    await expect(repository.generate()).rejects.toBe(failure);
  });

  it("rejects an empty generation response", async () => {
    const rpc = vi.fn().mockResolvedValue({ data: [], error: null });
    const repository = createPersonalInvitationRepository({
      rpc,
    } as unknown as JojoAuthClient);

    await expect(repository.generate()).rejects.toThrow(
      "Invitation generation returned no code.",
    );
  });
});
