create table if not exists public.redstar_messages (
  id bigint generated by default as identity primary key,
  content text not null check (char_length(btrim(content)) between 1 and 500),
  author text not null default '匿名' check (char_length(btrim(author)) between 1 and 50),
  created_at timestamptz not null default now()
);

alter table public.redstar_messages enable row level security;

create policy "redstar messages are publicly readable"
  on public.redstar_messages
  for select
  to anon, authenticated
  using (true);

create policy "visitors can leave redstar messages"
  on public.redstar_messages
  for insert
  to anon, authenticated
  with check (
    char_length(btrim(content)) between 1 and 500
    and char_length(btrim(author)) between 1 and 50
  );

grant select, insert on public.redstar_messages to anon, authenticated;
grant usage, select on sequence public.redstar_messages_id_seq to anon, authenticated;

create index if not exists redstar_messages_created_at_idx
  on public.redstar_messages (created_at desc, id desc);
